const fs = require('fs');
const p = process.argv[2], outDir = process.argv[3];
const top = JSON.parse(fs.readFileSync(p, 'utf8'));
const d = top.result || top;
const s = d.synthesis || {};
const agentCount = top.agentCount || top.agent_count || 40;
fs.mkdirSync(outDir, { recursive: true });
const findings = d.findings || [];
fs.writeFileSync(outDir + '/findings.json', JSON.stringify(findings, null, 2));
fs.writeFileSync(outDir + '/run_meta.json', JSON.stringify({ tier: d.tier, register: d.register, agent_count: agentCount, counts: d.counts, roster: d.roster, coverage: d.coverage }, null, 2));

const pick = (pred, n) => findings.filter(pred).slice(0, n);
const sample = [...pick(f => f.severity === 'High', 3), ...pick(f => f.severity === 'Medium', 2), ...pick(f => f.finding_type === 'absence-silence', 2)];
const seen = new Set();
const uniq = sample.filter(f => { if (seen.has(f.id)) return false; seen.add(f.id); return true; });

const L = [];
L.push('# Self-audit: CRUCIBLE run on its own design (Act I)');
L.push('');
L.push('A real, unedited Act I run of `paper-workshop` **on its own design** — SKILL.md + README +');
L.push('grounding rules + verification panel + the design doc, concatenated into one "manuscript."');
L.push('The tool eating its own dog food. Register **brutal**, mode **Roundtable** (`quick`, the');
L.push('cheapest fleet). Generated by `examples/parse_selfaudit.js` from the raw run.');
L.push('');
L.push('**Run:** ' + d.counts.raw_findings + ' raw findings → **' + d.counts.delivered + ' delivered**, ' +
  d.counts.rejected + ' rejected by the verification panel · ' + d.roster.seats + ' expert seats + ' +
  d.roster.generalists + ' generalists · **' + agentCount + ' agents total** · detected paper type: ' +
  (d.roster.paper_type || []).join(', ') + '.');
L.push('');
L.push('## The chair’s verdict');
L.push('');
L.push('> ' + (s.verdict || '(synthesis unavailable)'));
L.push('');
if (s.validity_verdict) { L.push('**Validity verdict.** ' + s.validity_verdict); L.push(''); }
if (s.venue_verdict) { L.push('**Venue read.** `' + s.venue_verdict.bucket + '` — ' + (s.venue_verdict.swing_factor || '')); L.push(''); }
if ((s.top_strengths || []).length) { L.push('**Top strengths.**'); (s.top_strengths || []).forEach(x => L.push('- ' + x)); L.push(''); }
const must = (s.prioritized_findings || []).filter(x => x.priority === 'must');
if (must.length) { L.push('**Must-fix (prioritized).**'); must.forEach(x => L.push('- **' + x.finding_id + '** — ' + x.one_line + ' _(' + x.panel_summary + ')_')); L.push(''); }
if ((s.kill_shots || []).length) { L.push('**Kill shots (verbatim, desk-reject pre-mortem — routed around the chair).**'); (s.kill_shots || []).forEach(x => { L.push(''); L.push('> ' + x); }); L.push(''); }
if (s.minority_report) { L.push('**Minority report.** ' + s.minority_report); L.push(''); }

L.push('## Central tensions the panel surfaced');
L.push('');
(d.roster.central_tensions || []).forEach((t, i) => { L.push((i + 1) + '. ' + t); });
L.push('');
L.push('## A representative sample of findings');
L.push('');
L.push('_(Full machine-readable set of all ' + d.counts.delivered + ' in `findings.json`.)_');
L.push('');
uniq.forEach(f => {
  L.push('### ' + f.id + ' · ' + f.severity + ' · ' + f.finding_type + ' · ' + (f.seat_id || ''));
  const loc = f.location ? (f.location.section || '') + (f.location.sentence_range ? ' (' + f.location.sentence_range + ')' : '') : '';
  if (loc) L.push('- **Location:** ' + loc);
  if (f.quote) L.push('- **Quote:** “' + String(f.quote).slice(0, 280) + '”');
  L.push('- **Issue:** ' + f.issue);
  L.push('- **Why it matters:** ' + f.why_it_matters);
  if (f.proposed_fix) L.push('- **Proposed fix:** ' + f.proposed_fix);
  L.push('- **Verification status:** `' + f.verification_status + '`');
  L.push('');
});
L.push('## Points rejected under scrutiny');
L.push('');
L.push('_The verification panel killed these — the gate is not a rubber stamp._');
L.push('');
(d.rejected_in_panel || []).forEach(r => L.push('- ' + r.suggestion + ' _(rejected: ' + r.why_rejected + ')_'));
L.push('');
L.push('## What this demonstrates');
L.push('');
L.push('- The fleet ran at **' + agentCount + ' agents** (batched verification keeps it bounded), produced **' +
  d.counts.delivered + ' grounded findings**, and the panel **rejected ' + d.counts.rejected + '** — the multi-angle gate does real work.');
L.push('- Findings are specific and self-critical: it caught a genuine inconsistency between the shipped SKILL.md and the design doc, and pressed on whether the architecture’s own guarantees are real or aspirational.');
L.push('- This is **Act I** (review) only. Act II (the rebuild — redline + clean version + re-run code + replication package) applies to papers that ship source, data, and code.');
fs.writeFileSync(outDir + '/REPORT.md', L.join('\n'));

console.log('VERDICT:', (s.verdict || '(none)').slice(0, 600));
console.log('counts:', JSON.stringify(d.counts), 'agents:', agentCount);
console.log('must-fix:', must.length, '| kill_shots:', (s.kill_shots || []).length, '| strengths:', (s.top_strengths || []).length);
console.log('venue:', s.venue_verdict ? s.venue_verdict.bucket : 'n/a');
console.log('wrote REPORT.md, findings.json, run_meta.json to', outDir);
